-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- Create categories table
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    description text,
    image_url text,
    icon_url text,
    parent_id bigint references public.categories(id),
    order_index integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies for categories
alter table public.categories enable row level security;

create policy "Allow public read access to categories"
    on public.categories for select
    to anon
    using (true);

-- Create products table
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    image_url text,
    category_id bigint references public.categories(id) not null,
    reference text,
    composition jsonb not null default '{}'::jsonb,
    technique text,
    width text,
    weight text,
    martindale text,
    repeats text,
    end_use text,
    price decimal(10,2),
    is_featured boolean not null default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies for products
alter table public.products enable row level security;

create policy "Allow public read access to products"
    on public.products for select
    to anon
    using (true);

-- Create product colors table
create table if not exists public.product_colors (
    id bigint generated by default as identity primary key,
    product_id bigint references public.products(id) not null,
    name text not null,
    color_code text not null,
    image_url text not null,
    is_default boolean not null default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies for product colors
alter table public.product_colors enable row level security;

create policy "Allow public read access to product colors"
    on public.product_colors for select
    to anon
    using (true);

-- Create product care instructions table
create table if not exists public.product_care_instructions (
    id bigint generated by default as identity primary key,
    product_id bigint references public.products(id) not null,
    icon text not null,
    instruction text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies for product care instructions
alter table public.product_care_instructions enable row level security;

create policy "Allow public read access to product care instructions"
    on public.product_care_instructions for select
    to anon
    using (true);

-- Add some sample data for categories
insert into public.categories (name, slug, description, image_url, icon_url, parent_id, order_index) values
('CURTAINS & DRAPES', 'curtains-and-drapes', 'Explore our collection of luxury curtains and drapes', 'https://example.com/curtains.jpg', 'https://ik.imagekit.io/sedar/icons/curtains.svg', null, 1),
('BLINDS & SHADES', 'blinds-and-shades', 'Discover our premium blinds and shades', 'https://example.com/blinds.jpg', 'https://ik.imagekit.io/sedar/icons/blinds.svg', null, 2),
('WALLPAPER', 'wallpaper', 'Transform your space with our wallpaper collection', 'https://example.com/wallpaper.jpg', 'https://ik.imagekit.io/sedar/icons/wallpaper.svg', null, 3),
('SMART HOME', 'smart-home', 'Smart home automation solutions', 'https://example.com/smart-home.jpg', 'https://ik.imagekit.io/sedar/icons/smart-home.svg', null, 4),
('FOLDING DOORS', 'folding-doors', 'Elegant folding door solutions', 'https://example.com/folding-doors.jpg', 'https://ik.imagekit.io/sedar/icons/folding-doors.svg', null, 5),
('OUTDOOR', 'outdoor', 'Outdoor furnishing solutions', 'https://example.com/outdoor.jpg', 'https://ik.imagekit.io/sedar/icons/outdoor.svg', null, 6),
('FURNISHINGS', 'furnishings', 'Complete your space with our furnishings', 'https://example.com/furnishings.jpg', 'https://ik.imagekit.io/sedar/icons/furnishings.svg', null, 7);

-- Update the categories for Curtains & Drapes with all subcategories and icons
with curtains_id as (select id from public.categories where slug = 'curtains-and-drapes' limit 1)
insert into public.categories (name, slug, parent_id, order_index, icon_url) values
('Pinch Pleat Curtains', 'pinch-pleat-curtains', (select id from curtains_id), 1, 'https://ik.imagekit.io/sedar/icons/pinch-pleat.svg'),
('Ripple Fold Curtains', 'ripple-fold-curtains', (select id from curtains_id), 2, 'https://ik.imagekit.io/sedar/icons/ripple-fold.svg'),
('Blackout Curtains', 'blackout-curtains', (select id from curtains_id), 3, 'https://ik.imagekit.io/sedar/icons/blackout.svg'),
('Grommet Eyelet Curtains', 'grommet-eyelet-curtains', (select id from curtains_id), 4, 'https://ik.imagekit.io/sedar/icons/grommet-eyelet.svg'),
('Sheer Curtains', 'sheer-curtains', (select id from curtains_id), 5, 'https://ik.imagekit.io/sedar/icons/sheer.svg'),
('Tailored Pleat Curtains', 'tailored-pleat-curtains', (select id from curtains_id), 6, 'https://ik.imagekit.io/sedar/icons/tailored-pleat.svg'),
('Goblet Pleat Curtains', 'goblet-pleat-curtains', (select id from curtains_id), 7, 'https://ik.imagekit.io/sedar/icons/goblet-pleat.svg'),
('Rod Pocket Curtains', 'rod-pocket-curtains', (select id from curtains_id), 8, 'https://ik.imagekit.io/sedar/icons/rod-pocket.svg'),
('Rod Loop Curtains', 'rod-loop-curtains', (select id from curtains_id), 9, 'https://ik.imagekit.io/sedar/icons/rod-loop.svg'),
('Inverted Pleat Curtains', 'inverted-pleat-curtains', (select id from curtains_id), 10, 'https://ik.imagekit.io/sedar/icons/inverted-pleat.svg'),
('Hospital & Medical Curtains', 'hospital-medical-curtains', (select id from curtains_id), 11, 'https://ik.imagekit.io/sedar/icons/hospital-medical.svg'),
('Theatre & Stage Curtain', 'theatre-stage-curtain', (select id from curtains_id), 12, 'https://ik.imagekit.io/sedar/icons/theatre-stage.svg'),
('Pencil Pleat Curtains', 'pencil-pleat-curtains', (select id from curtains_id), 13, 'https://ik.imagekit.io/sedar/icons/pencil-pleat.svg'),
('Curtain with Swarovski Crystals', 'curtain-with-swarovski-crystals', (select id from curtains_id), 14, 'https://ik.imagekit.io/sedar/icons/swarovski.svg'),
('Curtain with Embroidery', 'curtain-with-embroidery', (select id from curtains_id), 15, 'https://ik.imagekit.io/sedar/icons/embroidery.svg'),
('Curtain with customized printing designs', 'curtain-with-customized-printing', (select id from curtains_id), 16, 'https://ik.imagekit.io/sedar/icons/custom-print.svg'),
('Accessories', 'curtain-accessories', (select id from curtains_id), 17, 'https://ik.imagekit.io/sedar/icons/accessories.svg'),
('Hardware', 'curtain-hardware', (select id from curtains_id), 18, 'https://ik.imagekit.io/sedar/icons/hardware.svg');

-- Add sample products for Curtains & Drapes category
with categories_ids as (
    select id, slug from public.categories
    where slug in (
        'pinch-pleat-curtains',
        'ripple-fold-curtains',
        'blackout-curtains',
        'grommet-eyelet-curtains',
        'sheer-curtains',
        'tailored-pleat-curtains'
    )
)
insert into public.products (
    name,
    description,
    image_url,
    category_id,
    reference,
    composition,
    technique,
    width,
    weight,
    martindale,
    repeats,
    end_use,
    price,
    is_featured
)
select
    case c.slug
        when 'pinch-pleat-curtains' then 'Luxe Velvet Pinch Pleat'
        when 'ripple-fold-curtains' then 'Wave Silk Ripple Fold'
        when 'blackout-curtains' then 'Total Blackout Elite'
        when 'grommet-eyelet-curtains' then 'Modern Linen Eyelet'
        when 'sheer-curtains' then 'Ethereal Voile Sheer'
        when 'tailored-pleat-curtains' then 'Classic Tailored Pleat'
    end as name,
    case c.slug
        when 'pinch-pleat-curtains' then 'Elegant velvet curtains with deep pinch pleats for a luxurious look'
        when 'ripple-fold-curtains' then 'Smooth flowing silk curtains with modern ripple fold heading'
        when 'blackout-curtains' then 'Premium blackout curtains for complete light control'
        when 'grommet-eyelet-curtains' then 'Contemporary linen curtains with metal eyelets'
        when 'sheer-curtains' then 'Light and airy sheer curtains for soft natural light'
        when 'tailored-pleat-curtains' then 'Sophisticated tailored pleat curtains for a refined appearance'
    end as description,
    case c.slug
        when 'pinch-pleat-curtains' then 'https://example.com/curtains/pinch-pleat.jpg'
        when 'ripple-fold-curtains' then 'https://example.com/curtains/ripple-fold.jpg'
        when 'blackout-curtains' then 'https://example.com/curtains/blackout.jpg'
        when 'grommet-eyelet-curtains' then 'https://example.com/curtains/grommet.jpg'
        when 'sheer-curtains' then 'https://example.com/curtains/sheer.jpg'
        when 'tailored-pleat-curtains' then 'https://example.com/curtains/tailored.jpg'
    end as image_url,
    c.id as category_id,
    case c.slug
        when 'pinch-pleat-curtains' then 'PP-001'
        when 'ripple-fold-curtains' then 'RF-001'
        when 'blackout-curtains' then 'BO-001'
        when 'grommet-eyelet-curtains' then 'GE-001'
        when 'sheer-curtains' then 'SH-001'
        when 'tailored-pleat-curtains' then 'TP-001'
    end as reference,
    case c.slug
        when 'pinch-pleat-curtains' then '{"main": "100% Polyester Velvet"}'::jsonb
        when 'ripple-fold-curtains' then '{"main": "100% Silk"}'::jsonb
        when 'blackout-curtains' then '{"main": "100% Polyester", "backing": "Blackout Coating"}'::jsonb
        when 'grommet-eyelet-curtains' then '{"main": "100% Linen"}'::jsonb
        when 'sheer-curtains' then '{"main": "100% Polyester Voile"}'::jsonb
        when 'tailored-pleat-curtains' then '{"main": "100% Cotton"}'::jsonb
    end as composition,
    'Jacquard' as technique,
    '280cm' as width,
    case c.slug
        when 'pinch-pleat-curtains' then '320 g/m²'
        when 'ripple-fold-curtains' then '180 g/m²'
        when 'blackout-curtains' then '400 g/m²'
        when 'grommet-eyelet-curtains' then '250 g/m²'
        when 'sheer-curtains' then '80 g/m²'
        when 'tailored-pleat-curtains' then '280 g/m²'
    end as weight,
    '25,000' as martindale,
    'H: 64cm V: 64cm' as repeats,
    'Curtains & Drapes' as end_use,
    case c.slug
        when 'pinch-pleat-curtains' then 299.99
        when 'ripple-fold-curtains' then 399.99
        when 'blackout-curtains' then 249.99
        when 'grommet-eyelet-curtains' then 199.99
        when 'sheer-curtains' then 149.99
        when 'tailored-pleat-curtains' then 279.99
    end as price,
    true as is_featured
from categories_ids c;

-- Add sample product colors
with product_refs as (
    select id, reference from public.products where reference like 'PP-001'
)
insert into public.product_colors (
    product_id,
    name,
    color_code,
    image_url,
    is_default
)
values
    ((select id from product_refs), 'Royal Blue', '#1B4B8A', 'https://example.com/curtains/pinch-pleat-blue.jpg', true),
    ((select id from product_refs), 'Emerald Green', '#137547', 'https://example.com/curtains/pinch-pleat-green.jpg', false),
    ((select id from product_refs), 'Ruby Red', '#9B111E', 'https://example.com/curtains/pinch-pleat-red.jpg', false),
    ((select id from product_refs), 'Golden Yellow', '#FFD700', 'https://example.com/curtains/pinch-pleat-yellow.jpg', false);

-- Add sample care instructions
with product_refs as (
    select id, reference from public.products where reference like 'PP-001'
)
insert into public.product_care_instructions (
    product_id,
    icon,
    instruction
)
values
    ((select id from product_refs), '🧺', 'Dry clean only'),
    ((select id from product_refs), '🌡️', 'Do not tumble dry'),
    ((select id from product_refs), '👕', 'Do not bleach'),
    ((select id from product_refs), '🔨', 'Professional installation recommended');

-- Create function to update updated_at timestamp
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

-- Create triggers for updated_at
create trigger handle_updated_at
    before update on public.categories
    for each row
    execute function public.handle_updated_at();

create trigger handle_updated_at
    before update on public.products
    for each row
    execute function public.handle_updated_at();

create trigger handle_updated_at
    before update on public.product_colors
    for each row
    execute function public.handle_updated_at();

create trigger handle_updated_at
    before update on public.product_care_instructions
    for each row
    execute function public.handle_updated_at();
